title: "SPREE: A Spoofing Resistant GPS Receiver"
email: hello@spree-gnss.ch
description: > # this means to ignore newlines until "baseurl:"
  The first spoofing resistant GNSS Receiver
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.spree-gnss.ch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
